// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table ImportData (TimeStamp:datetime, Machine:string, TypeDevenement:string, Message:string) 
.create-or-alter table ImportData ingestion csv mapping 'ImportData_mapping'
```
[{"Properties":{"Ordinal":"0"},"column":"TimeStamp","datatype":""},{"Properties":{"Ordinal":"1"},"column":"Machine","datatype":""},{"Properties":{"Ordinal":"2"},"column":"TypeDevenement","datatype":""},{"Properties":{"Ordinal":"3"},"column":"Message","datatype":""}]
```
.create-merge table StockMarket (sector:string, AVG:real, Window_End_Time:datetime) 
